# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-02-28 12:01:41
"""
import arcpy
from arcpy.sa import *

def SIndexModel():  # SIndexModel

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("3D")
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")

    # Model Environment settings
    with arcpy.EnvManager(cartographicCoordinateSystem="PROJCS["NAD_1983_StatePlane_Vermont_FIPS_4400",GEOGCS["GCS_North_American_1983",DATUM["D_North_American_1983",SPHEROID["GRS_1980",6378137.0,298.257222101]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["False_Easting",500000.0],PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",-72.5],PARAMETER["Scale_Factor",0.9999642857142857],PARAMETER["Latitude_Of_Origin",42.5],UNIT["Meter",1.0]],VERTCS["Unknown VCS",VDATUM["Unknown"],PARAMETER["Vertical_Shift",0.0],PARAMETER["Direction",1.0],UNIT["Foot_US",0.3048006096012192]]", outputCoordinateSystem="PROJCS["NAD_1983_StatePlane_Vermont_FIPS_4400",GEOGCS["GCS_North_American_1983",DATUM["D_North_American_1983",SPHEROID["GRS_1980",6378137.0,298.257222101]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["False_Easting",500000.0],PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",-72.5],PARAMETER["Scale_Factor",0.9999642857142857],PARAMETER["Latitude_Of_Origin",42.5],UNIT["Meter",1.0]],VERTCS["Unknown VCS",VDATUM["Unknown"],PARAMETER["Vertical_Shift",0.0],PARAMETER["Direction",1.0],UNIT["Foot_US",0.3048006096012192]]", scratchWorkspace=r"C:\Users\Samuel\Documents\GEOG_592\SuitabilityModeling\Output.gdb\..\..\SuitabilityModeling\Output.gdb", 
                          snapRaster="Elevation"):
        Streams = "Streams"
        Elevation = arcpy.Raster("C:\\Users\\Samuel\\Documents\\GEOG_592\\SuitabilityModeling\\Data.gdb\\Elevation")
        LandUse = arcpy.Raster("C:\\Users\\Samuel\\Documents\\GEOG_592\\SuitabilityModeling\\Data.gdb\\LandUse")

        # Process: Distance Accumulation (Distance Accumulation) (sa)
        DistToStrm = "C:\\Users\\Samuel\\Documents\\GEOG_592\\SuitabilityModeling\\Output.gdb\\DistToStrm"
        Distance_Accumulation = DistToStrm
        blkRaster = "C:\\Users\\Samuel\\Documents\\GEOG_592\\SuitabilityModeling\\Output.gdb\\blkRaster"
        osdr = "C:\\Users\\Samuel\\Documents\\GEOG_592\\SuitabilityModeling\\Output.gdb\\osdr"
        oslr = "C:\\Users\\Samuel\\Documents\\GEOG_592\\SuitabilityModeling\\Output.gdb\\oslr"
        DistToStrm = arcpy.sa.DistanceAccumulation(in_source_data=Streams, in_barrier_data="", in_surface_raster="", in_cost_raster="", in_vertical_raster="", vertical_factor="BINARY 1 -30 30", in_horizontal_raster="", horizontal_factor="BINARY 1 45", out_back_direction_raster=blkRaster, out_source_direction_raster=osdr, out_source_location_raster=oslr, source_initial_accumulation="", source_maximum_accumulation="", source_cost_multiplier="", source_direction="", distance_method="PLANAR")
        DistToStrm.save(Distance_Accumulation)

        blkRaster = arcpy.Raster(blkRaster)
        osdr = arcpy.Raster(osdr)
        oslr = arcpy.Raster(oslr)

        # Process: Slope (Slope) (sa)
        SlopeMNew = "C:\\Users\\Samuel\\Documents\\GEOG_592\\SuitabilityModeling\\Output.gdb\\SlopeMNew"
        Slope = SlopeMNew
        SlopeMNew = arcpy.sa.Slope(in_raster=Elevation, output_measurement="DEGREE", z_factor=0.30480060960121924, method="PLANAR", z_unit="METER")
        SlopeMNew.save(Slope)


        # Process: Reclassify (Reclassify) (sa)
        Rcl_slope = "C:\\Users\\Samuel\\Documents\\GEOG_592\\SuitabilityModeling\\Data.gdb\\Rcl_slope"
        Reclassify = Rcl_slope
        Rcl_slope = arcpy.sa.Reclassify(in_raster=SlopeMNew, reclass_field="VALUE", remap="0 3 1;3 10 3;10 25 6;25 90 10", missing_values="DATA")
        Rcl_slope.save(Reclassify)


        # Process: Reclassify (2) (Reclassify) (sa)
        Rcl_landuse = "C:\\Users\\Samuel\\Documents\\GEOG_592\\SuitabilityModeling\\Output.gdb\\Rcl_landuse"
        Reclassify_2_ = Rcl_landuse
        Rcl_landuse = arcpy.sa.Reclassify(in_raster=LandUse, reclass_field="VALUE", remap="1 1;2 1;3 1;4 2;5 8;6 10;7 10;8 10;9 6;10 2;11 10;12 1", missing_values="DATA")
        Rcl_landuse.save(Reclassify_2_)


        # Process: Rescale by Function (Rescale by Function) (sa)
        Resc_DistToStrm = "C:\\Users\\Samuel\\Documents\\GEOG_592\\SuitabilityModeling\\Output.gdb\\Resc_DistToStrm"
        Rescale_by_Function = Resc_DistToStrm
        Resc_DistToStrm = arcpy.sa.RescaleByFunction(in_raster=DistToStrm, transformation_function=[["MSSMALL", "", "", "", "", 1, 1, ""]], from_scale=1, to_scale=10)
        Resc_DistToStrm.save(Rescale_by_Function)


        # Process: Raster Calculator (Raster Calculator) (sa)
        SIndexMap = "C:\\Users\\Samuel\\Documents\\GEOG_592\\SuitabilityModeling\\Output.gdb\\SIndexMap"
        Raster_Calculator = SIndexMap
        SIndexMap =  Rcl_slope *0.3 + Rcl_landuse *0.3 + Resc_DistToStrm *0.4
        SIndexMap.save(Raster_Calculator)


if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(cellSize="Elevation", extent="439952.113762345 200181.284694512 513122.113762345 253671.284694512 PROJCS["NAD_1983_StatePlane_Vermont_FIPS_4400",GEOGCS["GCS_North_American_1983",DATUM["D_North_American_1983",SPHEROID["GRS_1980",6378137.0,298.257222101]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["False_Easting",500000.0],PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",-72.5],PARAMETER["Scale_Factor",0.9999642857142857],PARAMETER["Latitude_Of_Origin",42.5],UNIT["Meter",1.0]],VERTCS["Unknown VCS",VDATUM["Unknown"],PARAMETER["Vertical_Shift",0.0],PARAMETER["Direction",1.0],UNIT["Foot_US",0.3048006096012192]]", mask="Elevation", 
                          workspace=r"C:\Users\Samuel\Documents\GEOG_592\SuitabilityModeling\Output.gdb"):
        SIndexModel()


# Errors
#   Error 1 :  Couldnot get Environment Settings
